### ISSUE TITLE
copying cookies from supabase response does not work for chunked cookies

### ISSUE THREAD

**Issue by nikololay** [npbee/fresh-supabase-auth#1]
hey @npbee!

I had [your blogpost](https://www.npbee.me/posts/fresh-supabase-auth) bookmarked when i was starting off with fresh couple of days ago. Thank you for writing it, it was a great help.

I found a bug when looking at session refreshes and thought I'd let you know since your post is the top hit for `auth fresh deno`

tldr: session refresh is broken for chunked cookies. because of [reasons](https://github.com/denoland/deno/pull/5100#issuecomment-624978988) iterating over `resp.headers` only returns the latest value set per header:

```ts
const headers = new Headers();
headers.append('Set-Cookie', 'cookie1=value1');
headers.append('Set-Cookie', 'cookie2=value2');

// Console log the headers object directly
console.log(headers); // Shows only one Set-Cookie header

// Spread the headers into an array
console.log([...headers]); // Shows all Set-Cookie headers
```

afaict, the iteration behaviour is intentionally different between clients and servers and the original Headers spec was not meant for deno-kind-of-use-case.

anyway, here:
https://github.com/npbee/fresh-supabase-auth/blob/e0aa40606ad54ca47bfd980e1bb8ad8ce50cf1e6/plugins/auth.ts#L58

could be like this:

```ts
 for (const [key, value] of [...resp.headers]) { 
```

or (apparently) this

```ts
 for (const [key, value] of resp.headers.entries()) { 
```
 
to copy all the headers returned by supabase and fix the session refreshes.

**Comment by npbee** [comment]
Wow, TIL! Thanks for sending this over. Let me update the post and repo to fix.
